# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^add", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^bug", group = "Fixed" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Changed" },
  { message = "^change", group = "Changed" },
  { message = "^update", group = "Changed" },
  { message = "^improve", group = "Changed" },
  { message = "^bump", group = "Changed" },
  { message = "^doc", group = "Documentation" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^chore", group = "Miscellaneous" },
  { message = "^ci", group = "CI/CD" },
  { message = ".*", group = "Other" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
